### ISSUE TITLE
Error when parsing empty url() tag

### ISSUE THREAD

**Issue by domderen** [iAdramelk/postcss-urlrewrite#4]
Hey,

I have a case where I have to handle a css string that looks like this:

```css
div {
  background-image: url();
}
```

using a script like this:

```javascript
const fs = require('fs');

const postcss = require('postcss');
const urlRewrite = require('postcss-urlrewrite');

const cssContents = fs.readFileSync('./file.css', 'utf8');

const rewrittenCss = postcss(urlRewrite({imports: true, rules: url => url}))
.process(cssContents)
.css;

console.log(rewrittenCss);
```

But it fails with an error:

```
/Users/dominik/dev/project/node_modules/postcss/lib/lazy-result.js:273
            throw error;
            ^

TypeError: Cannot read property 'toString' of undefined
    at UrlHelper.getModifiedRule (/Users/dominik/dev/project/node_modules/postcss-helpers/lib/url.js:66:31)
    at /Users/dominik/dev/chromium-server/project/postcss-helpers/lib/urls.js:49:57
    at Array.forEach (native)
    at UrlsHelper.getModifiedRule (/Users/dominik/dev/project/node_modules/postcss-helpers/lib/urls.js:48:19)
    at updateDecl (/Users/dominik/dev/project/node_modules/postcss-urlrewrite/lib/urlrewrite.js:107:29)
    at /Users/dominik/dev/project/node_modules/postcss/lib/container.es6:151:28
    at /Users/dominik/dev/project/node_modules/postcss/lib/container.es6:109:26
    at Rule.each (/Users/dominik/dev/project/node_modules/postcss/lib/container.es6:77:22)
    at Rule.walk (/Users/dominik/dev/project/node_modules/postcss/lib/container.es6:108:21)
    at /Users/dominik/dev/project/node_modules/postcss/lib/container.es6:111:32
```

I know that empty `url()` doesn't make much sense, but I don't have control over the CSS file I'm parsing, and I think this plugin should at least gracefully handle such a case, and not throw an error.

Thanks in advance for any help!

**Comment by iAdramelk** [comment]
Thanks for you feedback! Will try to look at it in the weekend.

**Comment by domderen** [comment]
Hey, thanks for your response. Any chance you had a moment to have a look at it? I'd be happy to help, but would appreciate some direction where to look for the issue.

**Comment by iAdramelk** [comment]
Sorry. Was at the conference in China last week so wasn't able to fix it before. Should work now. Please test it.

**Comment by domderen** [comment]
Yeah, thanks very much, this solved the problem ;) Much appreciated!
